# Generated by Django 3.2.9 on 2022-01-05 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs3team1', '0002_auto_20211230_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
