# Generated by Django 3.2.9 on 2022-01-05 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs3team1', '0003_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cs3team1.category', verbose_name='カテゴリ'),
            preserve_default=False,
        ),
    ]
